# Generated by Django 3.2.8 on 2021-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_auto_20211213_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
