# Generated by Django 3.2.8 on 2021-12-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_alter_menu_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
