# Generated by Django 3.2.8 on 2021-12-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_userdata_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1),
        ),
    ]
