# Generated by Django 3.2.8 on 2021-12-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_alter_userdata_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='userating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor service'), (2, 'Average service'), (3, 'Good service'), (4, 'Very Good service'), (5, 'Excellent service')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='rating',
        ),
    ]
